# Generated by Django 3.1.4 on 2020-12-20 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_listing_closed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Bid Amount'),
        ),
    ]
